### ISSUE TITLE
Fix - build failing on Bionic and Focal

### ISSUE THREAD

**Issue by MichaelRyanGreer** [ros-industrial-consortium/tesseract_ros#114]
Build passes on Bionic and Focal after changing the descartes-light dependency from "version: master" to "version: 0.2.1"

I have this change on a branch locally, happy to generate a pull request if you'd add me to the repository.

**Comment by Levi-Armstrong** [comment]
You are correct. I forgot that PR #111 had not been merged which should have correct branches. I have restarted CI to confirm and will merge if it passes.
