### ISSUE TITLE
ROS Basic Plotting has 0.5s delay in clear()

### ISSUE THREAD

**Issue by mpowelson** [ros-industrial-consortium/tesseract_ros#14]
Is this there for a reason?

**Comment by mpowelson** [comment]
@Levi-Armstrong

**Comment by Levi-Armstrong** [comment]
The only reason would be to give rviz time to update before proceeding. It could be removed.

**Comment by mpowelson** [comment]
Ok good. I'll submit a PR soon

**Comment by mpowelson** [comment]
Fixed in #13
