### ISSUE TITLE
Add ability to apply additional commands to planning request

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial-consortium/tesseract_ros#56]
I think it would be useful have the ability to add additional commands to be applied to the environment prior to motion planning. On the planner server side it will clone the environment and apply the commands. The use case is you want to plane up front with two different end effectors but do not want to modify the main environment to do so. @mpowelson what do you think?

**Comment by Levi-Armstrong** [comment]
@mpowelson I was about to start working on integrating this feature. Do you see any issues?

**Comment by mpowelson** [comment]
No. I think this will be valuable.

**Comment by Levi-Armstrong** [comment]
Addresed in #59
