### ISSUE TITLE
What to do with tesseract_ros_python?

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial-consortium/tesseract_ros#72]
@johnwason What is the plan for the python wrappers in this repository?

**Comment by johnwason** [comment]
Is it still needed? All of the functionality is in the main repo now.

**Comment by Levi-Armstrong** [comment]
It looks like it only wrapped the tesseract_rosutils which is mostly message conversion utilities which is not in the main repository.

**Comment by johnwason** [comment]
I think we should just delete the module. If someone needs it we can add it back.
