### ISSUE TITLE
Environment monitor crashes when adding/removing links frequently

### ISSUE THREAD

**Issue by mpowelson** [ros-industrial-consortium/tesseract_ros#90]
I have not dug into this, and it could be on my side not catching something. However, when I add and remove links frequently (once  every minute or so) the environment monitor crashes every 15-20 minutes.

**Comment by Levi-Armstrong** [comment]
Is this using the most recent master? If so, it may be missing a mutex somewhere.

**Comment by mpowelson** [comment]
> Is this using the most recent master? If so, it may be missing a mutex somewhere.

Yes it is. That's what I am assuming.

**Comment by Levi-Armstrong** [comment]
@mpowelson I believe this has been resolved?

**Comment by mpowelson** [comment]
I believe so.
