### ISSUE TITLE
Message Type Mismatch in `example.rviz`

### ISSUE THREAD

**Issue by ben-greenberg** [ros-industrial-consortium/tesseract_ros#97]
Running the online planning example with the latest versions of tesseract packages on Noetic.

When rviz opens it tries to subscribe to `/tesseract/display_tool_path` as a PoseArray instead of as the MarkerArray which is being published on that topic.

https://github.com/ros-industrial-consortium/tesseract_ros/blob/c2defa7f486da6bb8fabe7533387ff0270494ecb/tesseract_ros_examples/config/examples.rviz#L320

https://github.com/ros-industrial-consortium/tesseract_ros/blob/c2defa7f486da6bb8fabe7533387ff0270494ecb/tesseract_rosutils/src/plotting.cpp#L66

**Comment by Levi-Armstrong** [comment]
Please reopen if not addressed by PR #98
